### ISSUE TITLE
Upgrading to 1.2: "contraint less@1.0.0 is not satisfied by less 2.5.0_2"

### ISSUE THREAD

**Issue by lgessler** [awatson1978/dictionary#2]
Been trying to get this project to work with 1.2 and I think it's almost there, but there's one problem: 

```
=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  

   While selecting package versions:
   error: Conflict: Constraint less@1.0.0 is not satisfied by less 2.5.0_2.
   Constraints on package "less":
   * less@=2.5.0_2 <- top level
   * less@1.0.0 <- clinical:ui-vocabulary 1.0.5
```

Not sure where to go with this--from what I understand about Less 2.5.0, it should handle Less that was written for 1.0.0 just fine, so there's probably something weird going on with the package manager here.

**Comment by awatson1978** [comment]
Just try editing the .meteor/packages file.  Change 'less' to 'less@2.5.0'.

**Comment by lgessler** [comment]
Thank you for the very swift response. Wouldn't that specify the version of the `less` package but not affect the version of `less` being demanded by `clinical:ui-vocabulary 1.0.5`? 

I tried putting `less@2.5.0` in my .meteor/packages file, but a similar error persists:

```
=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  

   While selecting package versions:
   error: Conflict: Constraint less@1.0.0 is not satisfied by less 2.5.0_2.
   Constraints on package "less":
   * less@2.5.0 <- top level
   * less@=2.5.0_2 <- top level
   * less@1.0.0 <- clinical:ui-vocabulary 1.0.5
```

**Comment by awatson1978** [comment]
Ah.  Good point.  Well, clone the clinical:ui-vocabulary package into the /packages directory, and update that dependency too.   :)

**Comment by lgessler** [comment]
Got it working, thank you :)

All the steps, for completeness in case someone runs into the same problem:

From the root of the web app, 

```
meteor remove clinical:ui-vocabulary
mkdir packages && cd packages
git clone https://github.com/awatson1978/clinical-ui-vocabulary/
vim packages.json 
```

Under `Package.onUse`, make sure `api.use('less@2.5.0_2')` is in there.

In case you get an error like `client/stylesheets/custom.bootstrap.less:1518:17: variable @form-group-margin-bottom is undefined`, just `rm client/stylesheets/custom.bootstrap.less` and it'll be autogenerated when you run.
